- hosts: localhost
  handlers:

    - name: Restart ElasticSearch
      service: name=elasticsearch state=restarted

  vars:
    - service_name: "{{ local_unit.split('/')[0] }}"

  tasks:

    - include: tasks/install-elasticsearch.yml
      tags:
        - ansible.available
      
    - name: Update configuration
      template: src={{ charm_dir }}/templates/elasticsearch.yml
                dest=/etc/elasticsearch/elasticsearch.yml
                mode=0644
                backup=yes
      notify:
        - Restart ElasticSearch

    - name: Open ES Port when exposed
      command: open-port 9200
      tags:
        - elasticsearch.available

    - name: Start ElasticSearch
      service: name=elasticsearch state=started
      tags:
        - ansible.available


