- name: Add apt key.
  apt_key: url={{ apt_key_url }} state=present id={{gpg_key_id}}
  when: apt_key_url != ""

- name: Add apt archive.
  apt_repository:
    repo: "{{ apt_repository }}"
    state: present
  when: apt_repository != ""

- name: Install dependent packages.
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - openjdk-7-jre-headless
    - ufw


